### ISSUE TITLE
Update numpy.mat() -> numpy.asmatrix()

### ISSUE THREAD

**Issue by brown170** [LLNL/fudge#14]
Here is a traceback showing the issue:
```
Traceback (most recent call last):
  File "/Users/dbrown/Desktop/fudge/brownies/bin/plot_evaluation.py", line 513, in <module>
    raise err
  File "/Users/dbrown/Desktop/fudge/brownies/bin/plot_evaluation.py", line 449, in <module>
    makeCrossSectionPlot(
  File "/Users/dbrown/Desktop/junk/venv/lib/python3.12/site-packages/brownies/BNL/plot_evaluation/__init__.py", line 612, in makeCrossSectionPlot
    rawEndfUnc.append(covariance.getUncertaintyVector(relative=False))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbrown/Desktop/junk/venv/lib/python3.12/site-packages/fudge/covariances/mixed.py", line 164, in getUncertaintyVector
    return self.toCovarianceMatrix().getUncertaintyVector(theData=theData,relative=relative)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbrown/Desktop/junk/venv/lib/python3.12/site-packages/fudge/covariances/mixed.py", line 224, in toCovarianceMatrix
    commonMatrix = numpy.mat( firstCovMtx.group( ( commonRowAxis.values.values, commonColAxis.values.values ),
                   ^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/numpy/__init__.py", line 400, in __getattr__
    raise AttributeError(
AttributeError: `np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.
```

**Comment by brown170** [comment]
This is fixed (everywhere) in my monster pull request

**Comment by mattooca** [comment]
Also now fixed on master
